# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 979ea6a2bc6f1c507f0551118e51627581f510c4dcfaab78e30f361c832a7a34d352fd1109151e054167e5ea049151e89a3358cfe649272443585dc40a0ca863

test:
  secret_key_base: 5fd262b2cf212fbe281bdb605cf8a3f54eaf0ddf4a8234ee203548cc93faa5baf11a7cd66ff3b4316ae0158589dbb838004720086c7936f2b0d913f9960fae3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
